### ISSUE TITLE
CMS supported?

### ISSUE THREAD

**Issue by ziyafenn** [amelki/cms-json#14]
Hey there. I tried to run it but getting error 
```
module.js:549
    throw err;
    ^
```

**Comment by vinyll** [comment]
My guess would be the node version.
This project was updated a year ago, it may be abandoned and node has evolved.
Try a node version that was stable in mid 2017

**Comment by yunhan** [comment]
@vinyll which version are you using? I met the same problem and tried using v7.0.0 but still got the error.

**Comment by amelki** [comment]
@ziyafenn @vinyll sorry for the late answer. Do you have a more detailed stack?
I tried to run cms-json and I got an error saying 'express' was missing. I just published a new version that fixes this issue. I'm with node 10.12.0 and npm 6.4.1, and everything seems to work fine on my side. Please let me know if you get a chance to try it again.

**Comment by vinyll** [comment]
Running `v10.5.0` now works fine with me.
However I had to run the following prior to run the server:

```
mkdir default
touch index.html default/{data.json,schema.json}
```

**Comment by amelki** [comment]
@vinyll. You're right, I just fixed the issue: now if you run cms-json without --schema / --model parameters, the program will run with a pair of default sample files (<install_dir>/cms-json/default/schema.json and <install_dir>/cms-json/default/model.json). 
Thanks for the report
