### ISSUE TITLE
Cannot add a top level node

### ISSUE THREAD

**Issue by jbergen** [amelki/cms-json#5]
First off, I think this is a great project you're working on! Perfect for small-infrequently changing websites like I need. I'm having some issues getting up and running though.

- I cannot add a top level node (same in demo http://tenorcms.com/)
- Because you cannot add nodes, starting with empty json files means you can't do anything
- hitting `save` triggers a 404 and no data is saved. URL changes to `http://localhost:3001/node//new_tree#` and UI goes blank
- deep linking does not persist on reload (e.g. navigating directly to `/node/pages` results in blank page.)

Thank you so much!

**Comment by amelki** [comment]
Thanks for opening the issue. I am having a look right now. I'll keep you posted.

**Comment by amelki** [comment]
Creating a separate issue for "deep linking does not persist on reload", which is unrelated to the rest. See #6

**Comment by amelki** [comment]
Add node to top root is now fixed - closing this issue (working on #7 now)

**Comment by amelki** [comment]
Reopening while playground is not updated

**Comment by amelki** [comment]
playground fixed, closing for good

**Comment by amelki** [comment]
Thanks again for spotting the issues - I introduced them few days ago. I definitely need to add some UI automated tests...

**Comment by jbergen** [comment]
Thanks for the super fast fix! I pulled the latest and it looks great! 👌
